name: Build Map on Push

on:
  push:
    paths:
      - 'properties.json'
      - 'generate_map.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install folium

    - name: Generate map
      run: python generate_map.py

    - name: Commit and push map
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs/index.html
        git commit -m "Auto: Update map" || echo "No changes"
        git push
